version: '3.8'

services:
  # ===================================
  # CLUSTER 1: Production-like cluster
  # ===================================
  
  # Cluster 1 - Master Node 1
  es01-cluster1:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: es01-cluster1
    environment:
      - node.name=es01-cluster1
      - cluster.name=production-cluster
      - cluster.initial_master_nodes=es01-cluster1,es02-cluster1
      - discovery.seed_hosts=es02-cluster1,es03-cluster1
      - node.roles=master,data,ingest
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - xpack.security.enabled=true
      - xpack.security.authc.api_key.enabled=true
      - ELASTIC_PASSWORD=elasticpassword123
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.license.self_generated.type=trial
      # Shard configuration
      - cluster.routing.allocation.total_shards_per_node=1000
      - index.number_of_shards=3
      - index.number_of_replicas=1
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es01-cluster1-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elastic-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  # Cluster 1 - Master Node 2
  es02-cluster1:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: es02-cluster1
    environment:
      - node.name=es02-cluster1
      - cluster.name=production-cluster
      - cluster.initial_master_nodes=es01-cluster1,es02-cluster1
      - discovery.seed_hosts=es01-cluster1,es03-cluster1
      - node.roles=master,data,ingest
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - xpack.security.enabled=true
      - xpack.security.authc.api_key.enabled=true
      - ELASTIC_PASSWORD=elasticpassword123
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.license.self_generated.type=trial
      # Shard configuration
      - cluster.routing.allocation.total_shards_per_node=1000
      - index.number_of_shards=3
      - index.number_of_replicas=1
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es02-cluster1-data:/usr/share/elasticsearch/data
    ports:
      - "9201:9200"
    networks:
      - elastic-network
    depends_on:
      - es01-cluster1
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  # Cluster 1 - Data Node
  es03-cluster1:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: es03-cluster1
    environment:
      - node.name=es03-cluster1
      - cluster.name=production-cluster
      - cluster.initial_master_nodes=es01-cluster1,es02-cluster1
      - discovery.seed_hosts=es01-cluster1,es02-cluster1
      - node.roles=data,ingest
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - xpack.security.enabled=true
      - xpack.security.authc.api_key.enabled=true
      - ELASTIC_PASSWORD=elasticpassword123
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.license.self_generated.type=trial
      # Shard configuration
      - cluster.routing.allocation.total_shards_per_node=1000
      - index.number_of_shards=3
      - index.number_of_replicas=1
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es03-cluster1-data:/usr/share/elasticsearch/data
    ports:
      - "9202:9200"
    networks:
      - elastic-network
    depends_on:
      - es01-cluster1
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  # ===================================
  # CLUSTER 2: Development cluster
  # ===================================
  
  # Cluster 2 - Master Node 1
  es01-cluster2:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: es01-cluster2
    environment:
      - node.name=es01-cluster2
      - cluster.name=development-cluster
      - cluster.initial_master_nodes=es01-cluster2
      - discovery.seed_hosts=es02-cluster2
      - node.roles=master,data,ingest
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=true
      - xpack.security.authc.api_key.enabled=true
      - ELASTIC_PASSWORD=devpassword456
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.license.self_generated.type=trial
      # Shard configuration for smaller dev cluster
      - cluster.routing.allocation.total_shards_per_node=500
      - index.number_of_shards=2
      - index.number_of_replicas=0
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es01-cluster2-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elastic-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  # Cluster 2 - Data Node
  es02-cluster2:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: es02-cluster2
    environment:
      - node.name=es02-cluster2
      - cluster.name=development-cluster
      - cluster.initial_master_nodes=es01-cluster2
      - discovery.seed_hosts=es01-cluster2
      - node.roles=data,ingest
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=true
      - xpack.security.authc.api_key.enabled=true
      - ELASTIC_PASSWORD=devpassword456
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.license.self_generated.type=trial
      # Shard configuration for smaller dev cluster
      - cluster.routing.allocation.total_shards_per_node=500
      - index.number_of_shards=2
      - index.number_of_replicas=0
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es02-cluster2-data:/usr/share/elasticsearch/data
    ports:
      - "9201:9200"
    networks:
      - elastic-network
    depends_on:
      - es01-cluster2
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  # ===================================
  # CLUSTER 3: Testing cluster
  # ===================================
  
  # Cluster 3 - Single Node (for testing)
  es01-cluster3:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: es01-cluster3
    environment:
      - node.name=es01-cluster3
      - cluster.name=testing-cluster
      - discovery.type=single-node
      - node.roles=master,data,ingest
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=true
      - xpack.security.authc.api_key.enabled=true
      - ELASTIC_PASSWORD=testpassword789
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.license.self_generated.type=trial
      # Shard configuration for single node
      - cluster.routing.allocation.total_shards_per_node=1000
      - index.number_of_shards=5
      - index.number_of_replicas=0
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es01-cluster3-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elastic-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

volumes:
  # Production Cluster volumes
  es01-cluster1-data:
    driver: local
  es02-cluster1-data:
    driver: local
  es03-cluster1-data:
    driver: local
  
  # Development Cluster volumes
  es01-cluster2-data:
    driver: local
  es02-cluster2-data:
    driver: local
  
  # Testing Cluster volumes
  es01-cluster3-data:
    driver: local

networks:
  elastic-network:
    driver: bridge