// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['main']['App']['Close']();
}

export function CreateConfig(arg1) {
  return window['go']['main']['App']['CreateConfig'](arg1);
}

export function DeleteConfig(arg1) {
  return window['go']['main']['App']['DeleteConfig'](arg1);
}

export function ExecuteElasticsearchRequest(arg1) {
  return window['go']['main']['App']['ExecuteElasticsearchRequest'](arg1);
}

export function GetAllConfigs() {
  return window['go']['main']['App']['GetAllConfigs']();
}

export function GetClusterDashboardData() {
  return window['go']['main']['App']['GetClusterDashboardData']();
}

export function GetClusterDashboardDataByConfig(arg1) {
  return window['go']['main']['App']['GetClusterDashboardDataByConfig'](arg1);
}

export function GetClusterHealthForAllConfigs() {
  return window['go']['main']['App']['GetClusterHealthForAllConfigs']();
}

export function GetConfigByID(arg1) {
  return window['go']['main']['App']['GetConfigByID'](arg1);
}

export function GetDefaultConfig() {
  return window['go']['main']['App']['GetDefaultConfig']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HasDefaultConfig() {
  return window['go']['main']['App']['HasDefaultConfig']();
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function TestDefaultConnection() {
  return window['go']['main']['App']['TestDefaultConnection']();
}

export function UpdateConfig(arg1, arg2) {
  return window['go']['main']['App']['UpdateConfig'](arg1, arg2);
}
