// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CheckConnection(arg1:models.ConnectionTestRequest):Promise<models.ConnectionTestResponse>;

export function Close():Promise<void>;

export function CreateConfig(arg1:models.CreateConfigRequest):Promise<models.Config>;

export function DeleteConfig(arg1:number):Promise<void>;

export function GetAllConfigs():Promise<Array<models.Config>>;

export function GetClusterDashboardData(arg1:number):Promise<models.ProcessedDashboardData>;

export function GetClusterHealth(arg1:models.ConnectionTestRequest):Promise<models.ClusterHealth>;

export function GetConfigByID(arg1:number):Promise<models.Config>;

export function GetDefaultConfig():Promise<models.Config>;

export function HasDefaultConfig():Promise<boolean>;

export function UpdateConfig(arg1:number,arg2:models.UpdateConfigRequest):Promise<models.Config>;
