// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function Close():Promise<void>;

export function CreateConfig(arg1:models.CreateConfigRequest):Promise<models.Config>;

export function DeleteConfig(arg1:number):Promise<void>;

export function ExecuteElasticsearchRequest(arg1:models.ElasticsearchRestRequest):Promise<models.ElasticsearchRestResponse>;

export function GetAllConfigs():Promise<Array<models.Config>>;

export function GetClusterDashboardData():Promise<models.ProcessedDashboardData>;

export function GetClusterDashboardDataByConfig(arg1:number):Promise<models.ProcessedDashboardData>;

export function GetClusterHealthForAllConfigs():Promise<Record<string, string>>;

export function GetConfigByID(arg1:number):Promise<models.Config>;

export function GetDefaultConfig():Promise<models.Config>;

export function Greet(arg1:string):Promise<string>;

export function HasDefaultConfig():Promise<boolean>;

export function TestConnection(arg1:models.TestConnectionRequest):Promise<models.TestConnectionResponse>;

export function TestDefaultConnection():Promise<models.TestConnectionResponse>;

export function UpdateConfig(arg1:number,arg2:models.UpdateConfigRequest):Promise<models.Config>;
